### ISSUE TITLE
[Configurations] Config data always get from mainnet

### ISSUE THREAD

**Issue by hoailinh1210** [CasperDash/casperdash-extension#317]
**Describe the bug**
```
	const storageKey =  getNetworkStorageKey('configurations', network);
``` 
Return the `configurations` key because the network is empty when using `getConfigKey`

**Comment by gaupoit** [comment]
This task seems to be affected the staking screen, doesn't it @hoailinh1210 ? Could you please list down the affected feature s / screes ? Cheers
