### ISSUE TITLE
[NFT] Allow user transfer NFT

### ISSUE THREAD

**Issue by hoailinh1210** [CasperDash/casperdash-extension#351]
**Is your feature request related to a problem? Please describe.**
 - User can transfer NFT with receiving address and custom network fee

**Comment by gaupoit** [comment]
Tested cases:

- [ ] EggForce
- [ ] Hammer
- [ ] Casper Punk
- [ ] Transfer Casper Punk to new account

**Comment by gaupoit** [comment]
hi @hoailinh1210 , please help to create improvement task with your concern about high gas fee while using session code for CEP78. Thanks.
